### ISSUE TITLE
Error in the production and pull-requests workflows

### ISSUE THREAD

**Issue by vplasencia** [privacy-scaling-explorations/zk-kit#280]
## Context

https://github.com/privacy-scaling-explorations/zk-kit/actions/runs/8836779105/job/24264124859

https://github.com/privacy-scaling-explorations/zk-kit/actions/runs/8909151442/job/24466017647?pr=279

**Comment by sripwoud** [comment]
@cedoor and are aware of this.

See https://github.com/privacy-scaling-explorations/zk-kit/pull/273#issuecomment-2082308950

The main root cause is that the single CDN we currently use to download the artifacts is throttling downloads. This happens especially when automating downloading artifacts concurrently.
2 actions to solve this:
1. use multiple CDNs and retry fetch mechanism: see #273 and https://github.com/privacy-scaling-explorations/zk-kit/pull/275#discussion_r1582994771
2. In the tests for the `-proof` packages, we should stop testing ALL the parameters cases (e.g poseidon for 2,3...16 inputs). This requires downloading all the artifacts which takes too long. Most importantly testing the correct proof generation for different parameters is in the scope of the **circuit** package, not the **`*-proof`** packages. See https://github.com/privacy-scaling-explorations/zk-kit/pull/275#discussion_r1580726688
