### ISSUE TITLE
SMT add error with poseidon2 hashing

### ISSUE THREAD

**Issue by ashpect** [privacy-scaling-explorations/zk-kit#303]
**Describe the bug**
https://zkkit.pse.dev/modules/_zk_kit_smt.html
Following this article , if you create a tree2 using poseidon2 and try adding big ints using tree2.add(BigInt(2),BigInt(2)) , the addition fails with the following error :

```
 throw new Error(`poseidon-lite: Incorrect M length, expected ${t} got ${M.length}`);
          ^
Error: poseidon-lite: Incorrect M length, expected 4 got 3
```

**To Reproduce**
Here is a sample code you can try to see the error :
```
import { ChildNodes, SMT } from "@zk-kit/smt"
import { poseidon2 } from "poseidon-lite"

const hash2 = (childNodes: ChildNodes) => poseidon2(childNodes)
const tree2 = new SMT(hash2, true)
console.log(tree2.root)
tree2.add(BigInt("2"),BigInt("2"))
console.log(tree2.root)
```
**Expected behavior**
Should add the node to the smt

**Screenshots**

**Technologies (please complete the following information):**

-   Node.js version : v18.12.0
-   NPM version : 8.19.2
-   Ts-node version : v10.9.2

**Additional context**
Upon digging into it, this error from Poseidon-lite occurs when you try to pack more stuff using a specific Poseidon  algo.

This is where the Poseidon-lite throws error, where M is the Poseidon type+1 like 3 in case of Poseidon2 hashing used, so inputs.length +1 = M (input length should be 2 in case of posedion2)
<img width="999" alt="Screenshot 2024-07-02 at 5 22 22 PM" src="https://github.com/privacy-scaling-explorations/zk-kit/assets/93992470/e2791b48-8545-4258-9ae5-004cd295db1a">

So, if I use any other than Poseidon2 to hash, it would throw error as it expects an algo that can hash2 Bigint's which is as expected :
<img width="1001" alt="Screenshot 2024-07-02 at 5 27 19 PM" src="https://github.com/privacy-scaling-explorations/zk-kit/assets/93992470/292c6480-7f4c-4fb8-888d-4cc4c8db998d">

Now the issue arises when I call add, where it tries to hash 3 inputs using poseidon2 hashing as clearly stated here.

<img width="986" alt="Screenshot 2024-07-02 at 5 29 41 PM" src="https://github.com/privacy-scaling-explorations/zk-kit/assets/93992470/ee6a6982-c5ae-4f13-b261-476e46d054d9">

This is all which I can deduce from the call-stack. 
If it is something I am missing from my side, pls let me know. If not, how can I resolve this.

**Comment by cedoor** [comment]
Hi @ashpect, thanks for pointing this out!

I see why we haven't caught it. The README file was updated with `poseidon-lite` but tests are still using with `circomlibjs`, which works because it exports a Poseidon function that supports different numbers of inputs. Instead, `poseidon2` only supports two parameters.

This should fix it:

```js
import { SMT } from "@zk-kit/smt"
import { poseidon2, poseidon3 } from "poseidon-lite"

const hash2 = (childNodes) => (childNodes.length === 2 ? poseidon2(childNodes) : poseidon3(childNodes))
const tree2 = new SMT(hash2, true)

console.log(tree2.root)

tree2.add(BigInt("2"), BigInt("2"))

console.log(tree2.root)
```

`poseidon-lite` doesn't have a `poseidon` function like `circomlibjs`, so you can either use `circomlibjs` or the previous code.

I think the code above is better because it only imports the constants Poseidon needs for 2 and 3 inputs. `circomlibjs`-`poseidon` import all of them: https://github.com/iden3/circomlibjs/blob/43cc582b100fc3459cf78d903a6f538e5d7f38ee/src/poseidon_opt.js#L13.

The main improvement of `poseidon-lite` in comparison with `circomlibjs`-`poseidon` is precisely the possibility of importing only a portion of constants, saving a lot of memory.

**Comment by ashpect** [comment]
Hi, Thanks for the quick response. I'm closing the issue.
