### ISSUE TITLE
Store a default `zeroes` value for incremental merkle trees

### ISSUE THREAD

**Issue by vimwitch** [privacy-scaling-explorations/zk-kit#42]
**Is your feature request related to a problem? Please describe.**
In the unirep project we need to create many trees over time. To do this we have to copy the `zeroes` mapping to each new `IncrementalTreeData` structure on initialization. This involves `depth` `SLOAD` and `SSTORE` operations.

**Describe the solution you'd like**
Store an optional `defaultZeroes` for the `IncrementalBinaryTree` library. Add a flag to the `IncrementalTreeData` `defaultZeroes` that will cause the implementation to use the zeroes included in the library.

**Describe alternatives you've considered**
Rolling a modified version of the incremental merkle tree ourselves.

**Additional context**

**Comment by cedoor** [comment]
Hey, using the same zero values for many groups could lead to some security issues. Please, see this Semaphore issue related to the Veradise report: https://github.com/semaphore-protocol/semaphore/issues/196.

Report: https://github.com/semaphore-protocol/semaphore/files/10513776/Semaphore_3.0.0_Audit.pdf (V-SEM-VUL-001).

In general, the best solution should be to create dynamic zero values, different for each group. Here the solution Semaphore adopted: https://github.com/semaphore-protocol/semaphore/pull/197.

In your case it might make sense to take the risk and keep using the same zero values to make it more efficient. However, it's something that could be implemented separately, on top of this lib, so that devs are free to do whether they prefer. What do you think?

**Comment by cedoor** [comment]
Just saw the `useDefaultZeroes = false`, that works! It doesn't affect the existing implementation. We should inform devs about the risks though, with a comment in the code maybe.

**Comment by vimwitch** [comment]
I think I understand the problem you're describing. I think it's important to keep in mind this is a general use merkle tree implementation, so it shouldn't worry much about application/protocol specific needs.

That said, could you solve the zero preimage problem by adding

```
component z = IsZero();
z.in <== calculateIdentityCommitment.out;
z.out === 0;
```
[here](https://github.com/semaphore-protocol/semaphore/blob/main/packages/circuits/semaphore.circom#L67)?

**Comment by cedoor** [comment]
Yes, that should solve the problem on Semaphore. But we needed a solution that wouldn't affect the circuit, to avoid making another ceremony.
